version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mape_quiz_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Jfafcuxnd29
      POSTGRES_DB: mape_quiz
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mape_quiz"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    name: mape_quiz_pgdata
